export const persons = [
    {
        id:1,
        name:'Naveen',
        year:'3rd A',
        designation:'Leader'
    },
    {
        id:2,
        name:'',
        year:'',
        desgination:''
    },
    {
        id:3,
        name:'',
        year:'',
        desgination:''
    },
    {
        id:4,
        name:'',
        year:'',
        desgination:''
    },
    {
        id:5,
        name:'',
        year:'',
        desgination:''
    },
    {
        id:6,
        name:'',
        year:'',
        desgination:''
    },
    {
        id:7,
        name:'',
        year:'',
        desgination:''
    },
    {
        id:8,
        name:'',
        year:'',
        desgination:''
    },
    {
        id:9,
        name:'',
        year:'',
        desgination:''
    },

     {
        id:10,
        name:'',
        year:'',
        desgination:''
    },
    {
        id:11,
        name:'',
        year:'',
        desgination:''
    },
    {
        id:12,
        name:'',
        year:'',
        desgination:''
    },
    {
        id:13,
        name:'',
        year:'',
        desgination:''
    },
    {
        id:14,
        name:'',
        year:'',
        desgination:''
    },
    {
        id:15,
        name:'',
        year:'',
        desgination:''
    },
    {
        id:16,
        name:'',
        year:'',
        desgination:''
    },
    {
        id:17,
        name:'',
        year:'',
        desgination:''
    },
    {
        id:18,
        name:'',
        year:'',
        desgination:''
    },
    {
        id:19,
        name:'',
        year:'',
        desgination:''
    },
    {
        id:20,
        name:'',
        year:'',
        desgination:''
    },
    {
        id:21,
        name:'',
        year:'',
        desgination:''
    },

     {
        id:22,
        name:'',
        year:'',
        desgination:''
    },
    {
        id:23,
        name:'',
        year:'',
        desgination:''
    },
    {
        id:24,
        name:'',
        year:'',
        desgination:''
    },
    {
        id:25,
        name:'',
        year:'',
        desgination:''
    },
    {
        id:26,
        name:'',
        year:'',
        desgination:''
    },
    {
        id:27,
        name:'',
        year:'',
        desgination:''
    },
    {
        id:28,
        name:'',
        year:'',
        desgination:''
    },
    {
        id:29,
        name:'',
        year:'',
        desgination:''
    },
    {
        id:30,
        name:'',
        year:'',
        desgination:''
    },
    {
        id:31,
        name:'',
        year:'',
        desgination:''
    },
    {
        id:32,
        name:'',
        year:'',
        desgination:''
    },
    {
        id:33,
        name:'',
        year:'',
        desgination:''
    },

     {
        id:34,
        name:'',
        year:'',
        desgination:''
    },
    {
        id:35,
        name:'',
        year:'',
        desgination:''
    },
    {
        id:36,
        name:'',
        year:'',
        desgination:''
    },
    {
        id:37,
        name:'',
        year:'',
        desgination:''
    },
]